export const cities = [
    "Warsaw",
    "London",
    "New York",
    "Tokyo",
    "Berlin",
    "Wroclaw",
    "Chicago",
    "Kyiv",
    "Lisbon",
    "Madrid",
    "Shanghai",
    "Los Angeles",
    "Paris",
    "Toronto",
    "Singapore",
    "Washington",
    "Barcelona",
    "Dubai",
    "Rome",
    "Kuwait"
]